### ISSUE TITLE
Excess logging?

### ISSUE THREAD

**Issue by rossPatton** [danielhusar/gulp-stylint#1]
![allclear](https://cloud.githubusercontent.com/assets/2379901/6591501/5a2e7c4c-c77e-11e4-80bd-8acd37290d84.png)

Compared to the raw npm module's ouput:

![rawallclear](https://cloud.githubusercontent.com/assets/2379901/6591518/7c389bec-c77e-11e4-9868-22406a5a9535.png)

**Comment by danielhusar** [comment]
It logs for every file separately right now, will fix it.

**Comment by rossPatton** [comment]
thanks man

**Comment by danielhusar** [comment]
Hey, with your raw module you are targeting more than one file ?
Anyway this is little bit tricky, because of how the gulp works, you get the files in stream so have to check them separately. (you can concat them but its a very bad idea)

Maybe you can pass some option that this default message can be turned off, or make ability to create custom reporter like jshint have.

**Comment by danielhusar** [comment]
In 1.1.0 we no longer log the default success message.
